# Generated by Django 5.2.17 on 2026-08-12 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_registration', '0002_parkingrate_booking_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_license', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('mini_bus', 'Mini Bus'), ('bike', 'Bike'), ('micro', 'Micro'), ('truck', 'Truck')], default='car', max_length=30)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('vehicle_length', models.FloatField()),
                ('vehicle_width', models.FloatField()),
                ('vehicle_height', models.FloatField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=14)),
                ('driver_license', models.CharField(max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='User who registered this vehicle.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Registration',
                'verbose_name_plural': 'Vehicle Registrations',
                'db_table': 'vehicle_registration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.DeleteModel(
            name='ParkingRate',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='vehicle_registration',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='slot',
        ),
        migrations.DeleteModel(
            name='vehicle_registration',
        ),
    ]
